const userActionTypes = {
  RESET_PASSWORD_PENDING: "RESET_PASSWORD_PENDING",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
  SET_USER_DATA: "SET_USER_DATA",
  // INTRO.JS
  CHANGE_TUTORIAL_SETTINGS: "CHANGE_TUTORIAL_SETTINGS",
};

export default userActionTypes;
