export const initialState = {
  tags: [],
  savedSearches: [],
  filterOptions: {
    sourceType: [],
    channel: [],
    tone: [],
    publication: [],
    author: [],
    customTags: [],
    countries: [],
    topics: [],
  },
  filterTotal: {
    sourceType: 100,
    channel: 100,
    tone: 100,
    publication: 100,
    author: 100,
    customTags: 100,
    circulation: 100,
    countries: 100,
    topics: 1305,
  },
  isPendingFilterOptionsSearch: false,
  isUpdateFeedFiltersPending: false,
  errorSaveSearch: false,
  feedResults: [],
  searchTagOptions: [],
};
