const actionTypes = {
  SEARCH_OBJECT_SET_COUNTRY: "SEARCH_OBJECT_SET_COUNTRY",
  SEARCH_OBJECT_SET_TONE: "SEARCH_OBJECT_SET_TONE",
  SEARCH_OBJECT_SET_DATA: "SEARCH_OBJECT_SET_DATA",
  SEARCH_OBJECT_SET_SOURCE_TYPE: "SEARCH_OBJECT_SET_SOURCE_TYPE",
  SEARCH_OBJECT_SET_TAGS: "SEARCH_OBJECT_SET_TAGS",
  SEARCH_OBJECT_SET_DATE: "SEARCH_OBJECT_SET_DATE",
  SEARCH_OBJECT_SET_TOPICS: "SEARCH_OBJECT_SET_TOPICS",
  SEARCH_OBJECT_RESET: "SEARCH_OBJECT_RESET",
  LOAD_SAVED_SEARCH: "LOAD_SAVED_SEARCH",
  SET_SELECTED_TAG: "SET_SELECTED_TAG",
};

export default actionTypes;
