export const top100Films = [
  { title: "Goodfellas", year: 1990, type: "Company" },
  { title: "The Matrix", year: 1999, type: "Brand" },
  { title: "Seven Samurai", year: 1954, type: "People" },
  { title: "City of God", year: 2002, type: "Brand" },
  { title: "Se7en", year: 1995, type: "Company" },
  { title: "The Silence of the Lambs", year: 1991, type: "Company" },
  { title: "It's a Wonderful Life", year: 1946, type: "Company" },
  { title: "Life Is Beautiful", year: 1997, type: "Company" },
  { title: "The Usual Suspects", year: 1995, type: "Company" },
  { title: "Léon: The Professional", year: 1994, type: "Company" },
  { title: "Spirited Away", year: 2001, type: "Topic" },
  { title: "Saving Private Ryan", year: 1998, type: "Topic" },
  { title: "American History X", year: 1998, type: "Topic" },
  { title: "Interstellar", year: 2014, type: "Topic" },
  { title: "Casablanca", year: 1942, type: "Topic" },
  { title: "City Lights", year: 1931, type: "Client classification" },
  { title: "Psycho", year: 1960, type: "Client classification" },
  { title: "The Green Mile", year: 1999, type: "Client classification" },
  { title: "The Intouchables", year: 2011, type: "Brand" },
  { title: "Modern Times", year: 1936, type: "Client classification" },
  {
    title: "Raiders of the Lost Ark",
    year: 1981,
    type: "Client classification",
  },
  { title: "Rear Window", year: 1954, type: "Client classification" },
  { title: "The Pianist", year: 2002, type: "Client classification" },
  { title: "The Departed", year: 2006, type: "People" },
  { title: "Back to the Future", year: 1985, type: "People" },
  { title: "Whiplash", year: 2014, type: "People" },
  { title: "Gladiator", year: 2000, type: "People" },
  { title: "Memento", year: 2000, type: "People" },
  { title: "The Prestige", year: 2006, type: "Product" },
  { title: "The Lion King", year: 1994, type: "Product" },
  { title: "Apocalypse Now", year: 1979, type: "Product" },
  { title: "Alien", year: 1979, type: "Brand" },
];
