const alertActionTypes = {
  SAVE_ALERT_PENDING: "SAVE_ALERT_PENDING",
  SAVE_ALERT_SUCCESS: "SAVE_ALERT_SUCCESS",
  SAVE_ALERT_ERROR: "SAVE_ALERT_ERROR",
  GET_SAVED_ALERTS_ERROR: "GET_SAVED_ALERTS_ERROR",
  GET_SAVED_ALERTS_SUCCESS: "GET_SAVED_ALERTS_SUCCESS",
  GET_SAVED_ALERTS_PENDING: "GET_SAVED_ALERTS_PENDING",
};

export default alertActionTypes;
