const listsActionTypes = {
  SAVE_AUTHORS_LISTS: "SAVE_AUTHORS_LISTS",
  SAVE_PUBLICATIONS_LISTS: "SAVE_PUBLICATIONS_LISTS",
  GET_AUTHORS_LISTS: "GET_AUTHORS_LISTS",
  GET_PUBLICATIONS_LISTS: "GET_PUBLICATIONS_LISTS",
  GET_LISTS_PENDING: "GET_PUBLICATIONS_LISTS_PENDING",
};

export default listsActionTypes;
